# Generated by Django 4.2 on 2023-04-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='fotos',
            new_name='foto',
        ),
    ]
